#!/usr/bin/env bash
set -Eeuo pipefail

CONFIG="${CONFIG:-config/local.yml}"
FLAVOR="${FLAVOR:-amphora-default}"
REPETITIONS="${REPETITIONS:-3}"
REBUILD="${REBUILD:-1}"
INCLUDE_BANDWIDTH="${INCLUDE_BANDWIDTH:-0}"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

PYTHON="${PYTHON:-${REPO_ROOT}/.venv/bin/python}"
ANSIBLE="${ANSIBLE:-${REPO_ROOT}/.venv/bin/ansible}"
FLOAT_CONFIG="${FLOAT_CONFIG:-state/runbook-floating-ip.yml}"

mkdir -p results
RUNBOOK_TS="$(date -u +%Y%m%dT%H%M%SZ)"
RUNBOOK_LOG="results/floating-ip-suite-${RUNBOOK_TS}.log"
exec > >(tee -a "${RUNBOOK_LOG}") 2>&1

trap 'rc=$?; echo; echo "ERROR: floating-IP runbook failed at line ${LINENO} (rc=${rc})"; echo "Log: ${RUNBOOK_LOG}"; exit "${rc}"' ERR

banner() {
  echo
  echo "======================================================================"
  echo "$*"
  echo "======================================================================"
}

[[ -f "${CONFIG}" ]] || { echo "ERROR: missing ${CONFIG}" >&2; exit 1; }
[[ -f scripts/benchmark.py ]] || { echo "ERROR: missing scripts/benchmark.py" >&2; exit 1; }
[[ -x "${PYTHON}" ]] || { echo "ERROR: missing ${PYTHON}" >&2; exit 1; }
[[ -x "${ANSIBLE}" ]] || { echo "ERROR: missing ${ANSIBLE}" >&2; exit 1; }

banner "Floating-IP benchmark configuration"
echo "repo:              ${REPO_ROOT}"
echo "source config:     ${CONFIG}"
echo "derived config:    ${FLOAT_CONFIG}"
echo "flavor:            ${FLAVOR}"
echo "repetitions:       ${REPETITIONS}"
echo "rebuild:           ${REBUILD}"
echo "include bandwidth: ${INCLUDE_BANDWIDTH}"
echo "log:               ${RUNBOOK_LOG}"

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "git commit:        $(git rev-parse HEAD)"
  if [[ -n "$(git status --short)" ]]; then
    echo
    echo "WARNING: repository has uncommitted changes:"
    git status --short
  fi
fi

banner "Validate source config"
"${PYTHON}" - "${CONFIG}" <<'PY'
import sys
from pathlib import Path
import yaml

cfg = yaml.safe_load(Path(sys.argv[1]).read_text()) or {}
errors = []

stages = (cfg.get("locust") or {}).get("stages") or []
if not stages:
    errors.append("locust.stages is missing or empty")
else:
    final = stages[-1] or {}
    if final.get("users") != 8000:
        errors.append(f"final locust stage users={final.get('users')!r}; expected 8000")
    if final.get("spawn_rate") != 1000:
        errors.append(f"final locust stage spawn_rate={final.get('spawn_rate')!r}; expected 1000")

start_users = (cfg.get("max_rps") or {}).get("start_users")
if start_users != 500:
    errors.append(f"max_rps.start_users={start_users!r}; expected 500")

external = (cfg.get("network") or {}).get("external_network")
if not external:
    errors.append("network.external_network must be set")

if errors:
    print("ERROR: source config is not ready for controlled FIP comparison:")
    for error in errors:
        print(f"  - {error}")
    raise SystemExit(2)

print("Source settings OK")
print("  final Locust stage: 8000 users @ 1000 users/sec")
print("  max_rps.start_users: 500")
print(f"  external network: {external}")
PY

if [[ "${REBUILD}" == "1" ]]; then
  banner "Destroy currently provisioned test infrastructure"
  make destroy CONFIG="${CONFIG}"

  banner "Reset generated state (historical results are preserved)"
  rm -rf state/*
  touch state/.gitkeep
fi

mkdir -p "$(dirname "${FLOAT_CONFIG}")"

banner "Create derived floating-IP config"
"${PYTHON}" - "${CONFIG}" "${FLOAT_CONFIG}" <<'PY'
import copy
import sys
from pathlib import Path
import yaml

src = Path(sys.argv[1])
dst = Path(sys.argv[2])

cfg = yaml.safe_load(src.read_text()) or {}
derived = copy.deepcopy(cfg)
derived.setdefault("benchmark", {})["traffic_path"] = "floating_ip"
derived.setdefault("generator_network", {})["mode"] = "auto"

dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text(
    "# AUTO-GENERATED by scripts/run_floating_ip_suite.sh\n"
    "# Source config is left unchanged.\n"
    + yaml.safe_dump(derived, sort_keys=False)
)

print(f"Wrote {dst}")
print("  benchmark.traffic_path: floating_ip")
print("  generator_network.mode: auto  # resolves to dedicated_external")
print("  generator_network.create:", derived.get("generator_network", {}).get("create", "<unset>"))
PY

if [[ "${REBUILD}" == "1" ]]; then
  banner "Provision fresh external/FIP test topology"
  make provision CONFIG="${FLOAT_CONFIG}"

  banner "Configure fresh external/FIP test topology"
  make configure CONFIG="${FLOAT_CONFIG}"
else
  banner "REBUILD=0: preserving currently provisioned infrastructure"
  echo "WARNING: use REBUILD=0 only when the current fleet was built for"
  echo "         floating_ip / dedicated_external topology."
fi

banner "Verify Ansible connectivity"
"${ANSIBLE}" all -m ping

banner "Verify backend HTTP service"
"${ANSIBLE}" backends -b -m shell -a   'curl -sf http://127.0.0.1:80/1024.bin >/dev/null && echo HTTP-OK'

banner "Show generator network/routing state"
"${ANSIBLE}" locust_workers -b -m shell -a   'echo "=== addresses ==="; ip -4 -br addr; echo "=== routes ==="; ip -4 route'

echo
echo "Expected path:"
echo "  Locust workers"
echo "    -> dedicated generator subnet/router"
echo "    -> external network"
echo "    -> load balancer floating IP"
echo "    -> Octavia VIP"
echo "    -> backend members"
echo
echo "Direct-to-backend baselines are intentionally skipped/unavailable in"
echo "dedicated_external topology."

SCENARIOS=(
  http_1k_keepalive
  http_1k_max_rps
  http_1k_connection_churn
  tls_passthrough_1k_keepalive
  tls_passthrough_1k_connection_churn
  tls_passthrough_1k_max_rps
  tls_termination_1k_keepalive
  tls_termination_1k_connection_churn
  tls_termination_1k_max_rps
)

if [[ "${INCLUDE_BANDWIDTH}" == "1" ]]; then
  SCENARIOS+=(
    http_64k_keepalive
    http_1m_keepalive
    tls_termination_64k_keepalive
  )
fi

banner "Start floating-IP benchmark suite"

completed=0
for scenario in "${SCENARIOS[@]}"; do
  banner "Benchmark $((completed + 1))/${#SCENARIOS[@]}: ${scenario}"

  "${PYTHON}" scripts/benchmark.py     --config "${FLOAT_CONFIG}"     --flavor "${FLAVOR}"     --scenario "${scenario}"     --repetitions "${REPETITIONS}"

  completed=$((completed + 1))
  echo "Completed: ${scenario}"
done

banner "Floating-IP suite complete"
echo "Completed ${completed}/${#SCENARIOS[@]} scenarios."
echo "Results directory: ${REPO_ROOT}/results"
echo "Runbook log:       ${REPO_ROOT}/${RUNBOOK_LOG}"
echo "Derived config:    ${REPO_ROOT}/${FLOAT_CONFIG}"

echo
echo "Refresh cross-path comparison artifacts with:"
echo "  make report"
echo
echo "Compare tenant_vip and floating_ip as separate populations."

echo
echo "Newest result directories:"
find results -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n'   | sort -nr   | head -40   | cut -d' ' -f2-

